sudo: required
dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '10'
  - '12'

addons:
  chrome: stable
  firefox: latest

env:
  - MOZ_HEADLESS=1

branches:
  only:
    - development
    - master

install:
  - npm ci

before_script:
  - npm run lint

before_deploy:
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish
    on:
      repo: axerunners/axecore-lib
      branch: master
      node_js: '12'
