language: node_js
sudo: required
services:
  - xvfb
addons:
 chrome: stable
branches:
 only:
   - develop
   - master
node_js:
- '8'
before_install:
  - export DISPLAY=:99.0
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm install
before_script:
  - npm run lint
after_script:
  - gulp coveralls
deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish
    on:
      repo: axerunners/axecore-lib
      branch: master
