sudo: required
dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '10'
  - '12'

addons:
  chrome: stable
  firefox: latest

env:
  - MOZ_HEADLESS=1

branches:
  only:
    - development
    - master

before_install:
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm ci

before_script:
  - npm run lint

deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish
    on:
      repo: dashevo/dashcore-lib
      branch: master
